[2024-02-20T13:06:00.522+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-20T13:05:53.352639+00:00 [queued]>
[2024-02-20T13:06:00.548+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-20T13:05:53.352639+00:00 [queued]>
[2024-02-20T13:06:00.549+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T13:06:00.579+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): read_raw_data_from_s3> on 2024-02-20 13:05:53.352639+00:00
[2024-02-20T13:06:00.600+0000] {standard_task_runner.py:60} INFO - Started process 950 to run task
[2024-02-20T13:06:00.605+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'read_raw_data_from_s3', 'manual__2024-02-20T13:05:53.352639+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpml7xq8q1']
[2024-02-20T13:06:00.610+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask read_raw_data_from_s3
[2024-02-20T13:06:00.650+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-20T13:06:00.738+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-20T13:05:53.352639+00:00 [running]> on host eb0fadca60cf
[2024-02-20T13:06:00.885+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='read_raw_data_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T13:05:53.352639+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T13:05:53.352639+00:00'
[2024-02-20T13:06:00.930+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-20T13:06:04.014+0000] {logging_mixin.py:188} INFO - data from s3 is read in the dag
[2024-02-20T13:06:04.016+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-20T13:06:04.029+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=read_raw_data_from_s3, execution_date=20240220T130553, start_date=20240220T130600, end_date=20240220T130604
[2024-02-20T13:06:04.114+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-20T13:06:04.169+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
