[2024-02-21T11:51:24.716+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-21T11:51:13.782609+00:00 [queued]>
[2024-02-21T11:51:24.729+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-21T11:51:13.782609+00:00 [queued]>
[2024-02-21T11:51:24.730+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T11:51:25.085+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): read_raw_data_from_s3> on 2024-02-21 11:51:13.782609+00:00
[2024-02-21T11:51:25.093+0000] {standard_task_runner.py:60} INFO - Started process 8706 to run task
[2024-02-21T11:51:25.415+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'read_raw_data_from_s3', 'manual__2024-02-21T11:51:13.782609+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpxzeac0ht']
[2024-02-21T11:51:25.417+0000] {standard_task_runner.py:88} INFO - Job 190: Subtask read_raw_data_from_s3
[2024-02-21T11:51:26.419+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-21T11:51:28.134+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-21T11:51:13.782609+00:00 [running]> on host b14d6cdb7c29
[2024-02-21T11:51:31.710+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='read_raw_data_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T11:51:13.782609+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-21T11:51:13.782609+00:00'
[2024-02-21T11:51:31.741+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-21T11:51:40.368+0000] {logging_mixin.py:188} INFO - data from s3 is read in the dag
[2024-02-21T11:51:40.371+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T11:51:40.382+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=read_raw_data_from_s3, execution_date=20240221T115113, start_date=20240221T115124, end_date=20240221T115140
[2024-02-21T11:51:40.446+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T11:51:40.472+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
