[2024-02-22T05:00:25.311+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training scheduled__2024-02-21T00:00:00+00:00 [queued]>
[2024-02-22T05:00:25.318+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training scheduled__2024-02-21T00:00:00+00:00 [queued]>
[2024-02-22T05:00:25.319+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T05:00:25.331+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_training> on 2024-02-21 00:00:00+00:00
[2024-02-22T05:00:25.338+0000] {standard_task_runner.py:60} INFO - Started process 298 to run task
[2024-02-22T05:00:25.340+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'model_training', 'scheduled__2024-02-21T00:00:00+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmp1oybvdse']
[2024-02-22T05:00:25.343+0000] {standard_task_runner.py:88} INFO - Job 287: Subtask model_training
[2024-02-22T05:00:25.356+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-22T05:00:25.389+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.model_training scheduled__2024-02-21T00:00:00+00:00 [running]> on host b14d6cdb7c29
[2024-02-22T05:00:25.453+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-21T00:00:00+00:00'
[2024-02-22T05:00:25.469+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-22T05:00:27.852+0000] {logging_mixin.py:188} INFO - data file imported from s3
[2024-02-22T05:00:27.854+0000] {logging_mixin.py:188} INFO - data imported from s3
[2024-02-22T05:00:27.948+0000] {logging_mixin.py:188} INFO -  RMSE: 0.843382705892889
[2024-02-22T05:00:27.950+0000] {logging_mixin.py:188} INFO -  MAE:  0.6395225291401055
[2024-02-22T05:00:27.951+0000] {logging_mixin.py:188} INFO -  R2:  0.048760233587299306
[2024-02-22T05:00:27.965+0000] {logging_mixin.py:188} INFO - predict result : 0.048760233587299306
[2024-02-22T05:00:29.756+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-22T05:00:29.764+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=model_training, execution_date=20240221T000000, start_date=20240222T050025, end_date=20240222T050029
[2024-02-22T05:00:29.820+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-22T05:00:29.835+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
