[2024-02-21T11:47:40.476+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-21T11:47:09.849909+00:00 [queued]>
[2024-02-21T11:47:40.487+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-21T11:47:09.849909+00:00 [queued]>
[2024-02-21T11:47:40.489+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T11:47:40.506+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_training> on 2024-02-21 11:47:09.849909+00:00
[2024-02-21T11:47:40.515+0000] {standard_task_runner.py:60} INFO - Started process 8411 to run task
[2024-02-21T11:47:40.519+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'model_training', 'manual__2024-02-21T11:47:09.849909+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmppi9ry93h']
[2024-02-21T11:47:40.521+0000] {standard_task_runner.py:88} INFO - Job 185: Subtask model_training
[2024-02-21T11:47:40.540+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-21T11:47:40.579+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-21T11:47:09.849909+00:00 [running]> on host b14d6cdb7c29
[2024-02-21T11:47:40.663+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T11:47:09.849909+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-21T11:47:09.849909+00:00'
[2024-02-21T11:47:40.683+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-21T11:47:45.447+0000] {logging_mixin.py:188} INFO - data file imported from s3
[2024-02-21T11:47:45.451+0000] {logging_mixin.py:188} INFO - data imported from s3
[2024-02-21T11:47:45.495+0000] {logging_mixin.py:188} INFO -  RMSE: 0.8528526258778343
[2024-02-21T11:47:45.497+0000] {logging_mixin.py:188} INFO -  MAE:  0.645031393708269
[2024-02-21T11:47:45.498+0000] {logging_mixin.py:188} INFO -  R2:  0.05367522047772455
[2024-02-21T11:47:45.505+0000] {logging_mixin.py:188} INFO - 0.05367522047772455
[2024-02-21T11:47:45.510+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T11:47:45.520+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=model_training, execution_date=20240221T114709, start_date=20240221T114740, end_date=20240221T114745
[2024-02-21T11:47:45.572+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T11:47:45.591+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
