[2024-02-22T05:28:10.822+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-22T05:28:02.390304+00:00 [queued]>
[2024-02-22T05:28:10.832+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-22T05:28:02.390304+00:00 [queued]>
[2024-02-22T05:28:10.833+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T05:28:10.849+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): read_raw_data_from_s3> on 2024-02-22 05:28:02.390304+00:00
[2024-02-22T05:28:10.858+0000] {standard_task_runner.py:60} INFO - Started process 2259 to run task
[2024-02-22T05:28:10.866+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'read_raw_data_from_s3', 'manual__2024-02-22T05:28:02.390304+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpfrnwm6qe']
[2024-02-22T05:28:10.871+0000] {standard_task_runner.py:88} INFO - Job 292: Subtask read_raw_data_from_s3
[2024-02-22T05:28:11.839+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-22T05:28:11.943+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-22T05:28:02.390304+00:00 [running]> on host b14d6cdb7c29
[2024-02-22T05:28:12.109+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='read_raw_data_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T05:28:02.390304+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-22T05:28:02.390304+00:00'
[2024-02-22T05:28:12.155+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-22T05:28:17.712+0000] {logging_mixin.py:188} INFO - data from s3 is read in the dag
[2024-02-22T05:28:17.715+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-22T05:28:17.723+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=read_raw_data_from_s3, execution_date=20240222T052802, start_date=20240222T052810, end_date=20240222T052817
[2024-02-22T05:28:17.779+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-22T05:28:17.803+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
