[2024-02-21T13:22:53.920+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-21T13:22:43.227567+00:00 [queued]>
[2024-02-21T13:22:53.932+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-21T13:22:43.227567+00:00 [queued]>
[2024-02-21T13:22:53.932+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T13:22:53.950+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): read_raw_data_from_s3> on 2024-02-21 13:22:43.227567+00:00
[2024-02-21T13:22:53.957+0000] {standard_task_runner.py:60} INFO - Started process 13096 to run task
[2024-02-21T13:22:53.960+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'read_raw_data_from_s3', 'manual__2024-02-21T13:22:43.227567+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmp39gilwub']
[2024-02-21T13:22:53.962+0000] {standard_task_runner.py:88} INFO - Job 200: Subtask read_raw_data_from_s3
[2024-02-21T13:22:53.980+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-21T13:22:54.012+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-21T13:22:43.227567+00:00 [running]> on host b14d6cdb7c29
[2024-02-21T13:22:54.090+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='read_raw_data_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T13:22:43.227567+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-21T13:22:43.227567+00:00'
[2024-02-21T13:22:54.110+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-21T13:22:56.625+0000] {logging_mixin.py:188} INFO - data from s3 is read in the dag
[2024-02-21T13:22:56.629+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T13:22:56.641+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=read_raw_data_from_s3, execution_date=20240221T132243, start_date=20240221T132253, end_date=20240221T132256
[2024-02-21T13:22:56.711+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T13:22:56.741+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
