[2024-02-20T12:16:57.384+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T12:16:38.138623+00:00 [queued]>
[2024-02-20T12:16:57.394+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T12:16:38.138623+00:00 [queued]>
[2024-02-20T12:16:57.395+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T12:16:57.410+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-02-20 12:16:38.138623+00:00
[2024-02-20T12:16:57.422+0000] {standard_task_runner.py:60} INFO - Started process 11425 to run task
[2024-02-20T12:16:57.425+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'upload_to_s3', 'manual__2024-02-20T12:16:38.138623+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpap9qo8fr']
[2024-02-20T12:16:57.427+0000] {standard_task_runner.py:88} INFO - Job 174: Subtask upload_to_s3
[2024-02-20T12:16:57.442+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-20T12:16:57.474+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T12:16:38.138623+00:00 [running]> on host 0980836b8fdf
[2024-02-20T12:16:57.546+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T12:16:38.138623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T12:16:38.138623+00:00'
[2024-02-20T12:16:57.885+0000] {base.py:83} INFO - Using connection ID 's3_conn' for task execution.
[2024-02-20T12:16:57.886+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-02-20T12:16:59.694+0000] {logging_mixin.py:188} INFO - datafile uploaded successfully
[2024-02-20T12:16:59.698+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-20T12:16:59.709+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=upload_to_s3, execution_date=20240220T121638, start_date=20240220T121657, end_date=20240220T121659
[2024-02-20T12:16:59.772+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-20T12:16:59.798+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
