[2024-02-20T10:26:26.795+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_data_from_s3 manual__2024-02-20T10:26:13.950758+00:00 [queued]>
[2024-02-20T10:26:26.811+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_data_from_s3 manual__2024-02-20T10:26:13.950758+00:00 [queued]>
[2024-02-20T10:26:26.812+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T10:26:26.834+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): read_data_from_s3> on 2024-02-20 10:26:13.950758+00:00
[2024-02-20T10:26:26.843+0000] {standard_task_runner.py:60} INFO - Started process 4104 to run task
[2024-02-20T10:26:26.846+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'read_data_from_s3', 'manual__2024-02-20T10:26:13.950758+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpin45u_9j']
[2024-02-20T10:26:26.850+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask read_data_from_s3
[2024-02-20T10:26:26.872+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-20T10:26:26.920+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.read_data_from_s3 manual__2024-02-20T10:26:13.950758+00:00 [running]> on host 0980836b8fdf
[2024-02-20T10:26:27.043+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='read_data_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T10:26:13.950758+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T10:26:13.950758+00:00'
[2024-02-20T10:26:27.093+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-20T10:26:31.749+0000] {logging_mixin.py:188} INFO - data from s3 is read in the dag
[2024-02-20T10:26:31.752+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-20T10:26:31.763+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=read_data_from_s3, execution_date=20240220T102613, start_date=20240220T102626, end_date=20240220T102631
[2024-02-20T10:26:31.816+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-20T10:26:31.845+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
