[2024-02-21T10:18:35.346+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-21T10:18:27.571516+00:00 [queued]>
[2024-02-21T10:18:35.580+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-21T10:18:27.571516+00:00 [queued]>
[2024-02-21T10:18:36.205+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T10:18:36.902+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): read_raw_data_from_s3> on 2024-02-21 10:18:27.571516+00:00
[2024-02-21T10:18:36.910+0000] {standard_task_runner.py:60} INFO - Started process 1218 to run task
[2024-02-21T10:18:37.126+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'read_raw_data_from_s3', 'manual__2024-02-21T10:18:27.571516+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmp27jf028e']
[2024-02-21T10:18:37.284+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask read_raw_data_from_s3
[2024-02-21T10:18:38.643+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-21T10:18:41.754+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-21T10:18:27.571516+00:00 [running]> on host b14d6cdb7c29
[2024-02-21T10:18:41.842+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='read_raw_data_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T10:18:27.571516+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-21T10:18:27.571516+00:00'
[2024-02-21T10:18:41.862+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-21T10:18:44.325+0000] {logging_mixin.py:188} INFO - data from s3 is read in the dag
[2024-02-21T10:18:44.328+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T10:18:44.341+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=read_raw_data_from_s3, execution_date=20240221T101827, start_date=20240221T101835, end_date=20240221T101844
[2024-02-21T10:18:44.387+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T10:18:44.423+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
