[2024-02-20T12:16:47.183+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-20T12:16:38.138623+00:00 [queued]>
[2024-02-20T12:16:47.195+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-20T12:16:38.138623+00:00 [queued]>
[2024-02-20T12:16:47.196+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T12:16:47.211+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): read_raw_data_from_s3> on 2024-02-20 12:16:38.138623+00:00
[2024-02-20T12:16:47.226+0000] {standard_task_runner.py:60} INFO - Started process 11367 to run task
[2024-02-20T12:16:47.242+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'read_raw_data_from_s3', 'manual__2024-02-20T12:16:38.138623+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpsabu1ja9']
[2024-02-20T12:16:47.248+0000] {standard_task_runner.py:88} INFO - Job 171: Subtask read_raw_data_from_s3
[2024-02-20T12:16:47.278+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-20T12:16:47.315+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.read_raw_data_from_s3 manual__2024-02-20T12:16:38.138623+00:00 [running]> on host 0980836b8fdf
[2024-02-20T12:16:47.399+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='read_raw_data_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T12:16:38.138623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T12:16:38.138623+00:00'
[2024-02-20T12:16:47.644+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-20T12:16:52.986+0000] {logging_mixin.py:188} INFO - data from s3 is read in the dag
[2024-02-20T12:16:52.988+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-20T12:16:52.996+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=read_raw_data_from_s3, execution_date=20240220T121638, start_date=20240220T121647, end_date=20240220T121652
[2024-02-20T12:16:53.045+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-20T12:16:53.066+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
